- hosts: root-target-server
  become: true
  tags: [runner]
  vars_files:
    - inventory/host_vars/github-actions-runner.yml
    - inventory/host_vars/github-actions-secret.yml
  roles:
    - role: github-actions-runner
      tags: runner
    - role: github-actions-secret
      tags: secret

- hosts: root-target-server
  become: true
  tags: [docker]
  vars_files:
    - inventory/host_vars/github-actions-runner.yml
    - inventory/host_vars/github-actions-secret.yml
  roles:
    - role: docker
      tags: docker

- hosts: root-target-server
  become: true
  tags: [certbot]
  vars_files:
    - inventory/host_vars/github-actions-runner.yml
    - inventory/host_vars/github-actions-secret.yml
  roles:
    - role: certbot
      tags: certbot
    
- hosts: root-target-server
  become: true
  tags: [harbor]
  vars_files:
    - inventory/host_vars/harbor.yml   
  roles:
    - role: robertdebock.harbor
      tags: harbor
    - role: harbor
      tags: harbor

- hosts: root-target-server
  tags: [forgejo]
  vars_files:
    - inventory/host_vars/forgejo.yml   
  roles:
    - role: forgejo
      tags: forgejo
