forgejo_url: "{{ lookup('env', 'FORGEJO_URL') }}"
forgejo_org_name: "{{ lookup('env', 'FORGEJO_ORG_NAME') }}"
forgejo_token: "{{ lookup('env', 'FORGEJO_TOKEN') }}"

secrets:
  - name: "REGISTRY_PASSWORD"
    value: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
  - name: "REGISTRY_URL"
    value: "{{ lookup('env', 'REGISTRY_URL') }}"
  - name: "REGISTRY_USERNAME"
    value: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
  - name: "VAULT_PASSWORD"
    value: "{{ lookup('env', 'VAULT_PASSWORD') }}"
  - name: "VAULT_PATH"
    value: "{{ lookup('env', 'VAULT_PATH') }}"
  - name: "VAULT_URL"
    value: "{{ lookup('env', 'VAULT_URL') }}"
  - name: "VAULT_USERNAME"
    value: "{{ lookup('env', 'VAULT_USERNAME') }}"