- name: "Processing Secrets for Repo: {{ current_repo }}"
  block:
    - name: Set Static Secrets via Forgejo API
      ansible.builtin.uri:
        url: "{{ forgejo_url }}/api/v1/repos/{{ forgejo_org_name }}/{{ current_repo }}/actions/secrets/{{ item.name }}"
        method: PUT
        status_code: [201, 204]
        body_format: json
        body:
          data: "{{ item.value }}"
        headers:
          Authorization: "token {{ forgejo_token }}"
          Content-Type: "application/json"
      loop: "{{ secrets }}"
      no_log: true

    - name: Set Dynamic VAULT_PATH Secret (kv/data/{{ current_repo }})
      ansible.builtin.uri:
        url: "{{ forgejo_url }}/api/v1/repos/{{ forgejo_org_name }}/{{ current_repo }}/actions/secrets/VAULT_PATH"
        method: PUT
        status_code: [201, 204]
        body_format: json
        body:
          data: "kv/data/{{ current_repo }}"
        headers:
          Authorization: "token {{ forgejo_token }}"
          Content-Type: "application/json"
      no_log: true